config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  get '/operations', to: 'operations#display'
  
  resources :categories do
    resources :operations, only: [:show, :edit, :update, :destroy, :index]
  end

  resources :operations, only: [:new, :create]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :operations, dependent: :destroy
    

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    
end

app/models/operation.rb
class Operation < ApplicationRecord
  enum :otype, { outlay: 0, income: 1 }, default: :outlay
  
  belongs_to :category

  validates :amount, numericality: { greater_than: 0 }
  validates :odate, presence: true
  validates :description, presence: true

  def self.search(search)
    where("category_id = #{search}")
  end

  def self.data_for_reports(start_date, end_date, otype)
    where('odate BETWEEN ? AND ? AND otype = ?', start_date, end_date, otype)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :notfound

  private

  def notfound
    render file: 'public/404.html', status: :not_found, layout:false
  end
end  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.page(params[:page])
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_category
      @category = Category.find(params[:id])
    end

    
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :get_category, except: %i[ display new create ]
  before_action :set_categories, only: %i[ new edit create update ]
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations
  def display
    if (params[:search]).present?
      @operations = Operation.search(params[:search]).order(created_at: :desc).page(params[:page])
    else
      @operations = Operation.order(created_at: :desc).page(params[:page])
    end
  end

  # GET category/id/operations
  def index
    @operations = @category.operations.page(params[:page])
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)
    
    respond_to do |format|
      if @operation.save
        format.html { redirect_to operations_path(@category), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operations_path(@category), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_path(@category), notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  
  private
    def get_category
      @category = Category.find(params[:category_id])
    end  
    
    def set_categories
      @categories = Category.all.map{ |cat| [ cat.name, cat.id ] }
    end 
  
    def set_operation
      @operation = @category.operations.find(params[:id])
    end

    def operation_params
      params.require(:operation).permit(:amount, :otype, :odate, :description, :category_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
 
  def index
  end

  def report_by_category

    @data = Operation.data_for_reports(params[:start_date], params[:end_date], params[:otype])
           .group("category_id").sum(:amount)

    @total = Operation.data_for_reports(params[:start_date], params[:end_date], params[:otype])
            .sum(:amount)

  #Preparing data for Chart.js
    pai_data = @data.transform_keys { |categ| Category.find_by(id: categ).name }.to_a
    
    @pai_name = pai_data.map { |e| e[0] }
    @pai_sum = pai_data.map { |e| e[1] }
  end

  
  def report_by_dates

    data_chart = Operation.data_for_reports(params[:start_date], params[:end_date], params[:otype])
                .group("odate").sum(:amount)

    @data_date = data_chart.map { |key, value| key.strftime('%Y-%m-%d') }
    @data_sum = data_chart.map { |key, value| value }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
    
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
    def operation_type
        Operation.otypes.keys.map do |type|
          [ type.titleize, type ]
        end
    end

end

app/helpers/reports_helper.rb
module ReportsHelper

end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category %>

<%= form_with(model: category) do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <br>
  <div class="btn-group mb-3">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div>
<h2>Editing category</h2>

<%= render "form", category: @category %>

</div>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="p-6">
<h1 style="color: black">Categories</h1>


<%= link_to "New category", new_category_path, class: "btn btn-info" %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% num = 1 %>
    <% @categories.each do |category| %>
    <tr>
      <th scope="row"><%= num %></th>
      <td><%= category.name %></td>
      <td><%= category.description %></td>
      <td class="btn-group"><%= link_to "Edit", edit_category_path(category), class: "btn btn-outline-success" %>
      <%= button_to "Delete", category, :method =>  'delete',
      form: {data: {turbo_confirm: 'Are you sure?'}}, class: "btn btn-outline-warning mx-1" %>
      <%= link_to "Operations", category_operations_path(category), class: "btn btn-outline-success" %></td>
    </tr>
    <% num += 1 %>
    <% end %>
 </tbody>
</table>
</div>

<%= paginate @categories %>

app/views/categories/new.html.erb
<div>
<h2>New category</h2>

<%= render "form", category: @category %>
</div>
<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<h2 style="color: black">Detail Information</h2>

<%= render @category %>


<div class="btn-group">
  <%= link_to "Edit", edit_category_path(@category), class: 'btn btn-info' %>
  <%= button_to "Delete", @category, :method =>  'delete',
   form: {data: {turbo_confirm: 'Are you sure?'}}, class: "btn btn-danger mx-1" %>
  <%= link_to "Back to categories", categories_path, class: 'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>

  
  <body>
   <%= render 'shared/header' %>
    <main class="container mt-3"
      <%= yield %>
    </main>
   <%= render 'shared/footer' %>
  </body>
</html>

app/views/main/index.html.erb
<div>
  <h1 class="text-success text-center">Welcome to CoinApp!</h1>
    <p class="fs-3", "text-center"> CoinApp - the financial planning, review,
       expense tracking, and personal asset management app.
        CoinApp makes managing personal finances as easy as pie!
        Now easily record your personal and business financial transactions,
      generate spending reports, review your daily, weekly and monthly financial data
    and manage your assets with CoinApp's spending tracker and budget planner.</p>
</div>
 

app/views/operations/_form.html.erb
<%= render 'shared/errors', object: @operation %>

<%= form_with(model: [@category, operation]) do |form| %>
  
  <p class="my-3">
    <%= form.label :amount, 'Amount:' %>
    <%= form.text_field :amount, placeholder: "Enter the price", required: true %>
  </p>

  <p class="my-3">
    <%= form.label :otype, 'Type operation:' %>
    <%= form.select(:otype, operation_type, {}) %>
  </p>

  <p class="my-3">
    <%= form.label :odate, 'Operation date:' %>
    <%= form.date_field :odate, required: true %>
  </p>

  <p class="my-3">
    <%= form.label :description, 'Description:' %>
    <%= form.text_field :description, required: true %>
  </p>

  <p class="my-3">
    <%= form.label :category, 'Category:' %>
    <%= select(:operation, :category_id, @categories) %>
  </p>
  
  <p class="my-3">
    <%= form.submit class: "btn btn-warning" %>
  </p>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <p>
    <strong>Amount:</strong>
    <%= operation.amount %>
  </p>

  <p>
    <strong>Type operation:</strong>
    <%= operation.otype %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= operation.odate.strftime('%Y-%m-%d') %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= operation.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= operation.category.name %>
  </p>

</div>

app/views/operations/display.html.erb
<p style="color: green"><%= notice %></p>

<h2 style="color: black">All Operations</h2>

<div>
<%= form_tag(operations_path, :method => "get", id: "search-form") do %>
  <%= select_tag :search, options_from_collection_for_select(Category.all, "id", "name"),
   { include_blank: "All category" } %>
  <%= submit_tag("Search by category", :name => nil) %>
<% end %>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category</th>
      <th scope="col">Operation type</th>
      <th scope="col">Sum</th>
      <th scope="col">Data</th>
      <th scope="col">Description</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% num = 1 %>
    <% @operations.each do |operation| %>
    <% category = operation.category %>
    <tr>
      <th scope="row"><%= num %></th>
      <td><%= operation.category.name %></td>
      <td><%= operation.otype %></td>
      <td><%= operation.amount %></td>
      <td><%= operation.odate.strftime('%Y-%m-%d') %></td>
      <td><%= operation.description %></td>
      <td><%= link_to "Show this operation", category_operation_path(category, operation),
        class: "btn btn-outline-success" %></td>
    </tr>
    <% num += 1 %>
    <% end %>
 </tbody>
</table>

<%= paginate @operations %>

<%= link_to "Add new operation", new_operation_path, class: "btn btn-info" %>

app/views/operations/edit.html.erb
<div>
  <h3>Editing operation</h3>
    <%= render "form", operation: @operation %>
</div>

<div>
  <%= link_to "Back", [@category, @operation], class: 'btn btn-success' %>
  <%= link_to "Back to operations", operations_path, class: 'btn btn-secondary' %>
</div>

app/views/operations/index.html.erb
<p style="color: green"><%= notice %></p>

  <h2 style="color: black">Operations in category "<%= Category.find(params[:category_id]).name %>"</h2>

<div class="p-4">
  <div id="operations">
    <% @operations.each do |operation| %>
      <%= render operation %>
        <p>
          <%= link_to "Show this operation", category_operation_path(@category, operation) %>
        </p>
    <% end %>
  </div>
    <%= paginate @operations %>
</div>

app/views/operations/new.html.erb
<div>
<h2 style="color: black">New operation</h2>

<%= render "form", operation: @operation %>

</div>

<div>
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<h2 style="color: black">Detail Information</h2>

<div>
<%= render @operation %>
</div>

<div class="btn-group">
  <%= link_to "Edit", edit_category_operation_path(@category, @operation), class: 'btn btn-info' %>
  <%= button_to "Delete", [@category, @operation], method: :delete,
  form: {data: {turbo_confirm: 'Are you sure?'}}, class: "btn btn-danger mx-1" %>
  <%= link_to "Back to operations", operations_path, class: 'btn btn-secondary' %>
</div>

app/views/reports/_pai_image.html.erb
<div>
  <canvas id="myChart" width="800" height="500"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart');
  
  const data = {
  labels: <%= raw @pai_name %>,
  datasets: [{
    label: 'Category sum',
    data: <%= @pai_sum %>,
    backgroundColor: [
        'rgb(39, 179, 245)',
        'rgb(161, 39, 245)',
        'rgb(255, 205, 86)',
        'rgb(108, 0, 125)',
        'rgb(0, 41, 125)',
        'rgb(224, 147, 187)',
        'rgb(245, 40, 145)',
        'rgb(39, 189, 93)',
        'rgb(255, 205, 76)'
      ], 
    hoverOffset: 4
  }]
};

const config = {
  type: 'pie',
  data: data,
  options: {
    responsive: false
  }
};

const myChart = new Chart(ctx, config);
</script>   
    

app/views/reports/index.html.erb
<div class="col-md-6">
  <h1>Reports</h1>
    <form action="index" method="GET">
    <div class="col-md-6">
      <label class="form-label"> Select start date: </label>
        <input class="form-control" type="date" name="start_date", required="true">
    </div>
       <div class="col-md-6">
         <label class="form-label"> Select end date: </label>
       <input class="form-control" type="date" name="end_date", required="true">
      </div>
    <div class="col-md-6"> 
      <label class="form-label"> Select type operation:</label>
        <select class="form-control" name="otype">
          <option value="0" selected>Outlay</option>
         <option value="1">Income</option>
        </select>
     </div>

   <div class="col-md-6">
     <br>
     <input type="submit" formaction="report_by_category" value="View report by category" class="btn btn-primary">
     <input type="submit" formaction="report_by_dates" value="View report by dates" class="btn btn-primary">
     </br>
   </div> 
  </div>
</form>

app/views/reports/report_by_category.html.erb
<div class="container-fluid">
  <h2>Financial Report by categories in the date range 
    <%= params[:start_date] %> - <%= params[:end_date] %></h2>

<div class="col-md-4" style="float:left;">
 <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Category</th>
      <th scope="col">Sum</th>
    </tr>
  </thead>
  <tbody>
    <% num = 1 %>
    <% @data.each_pair do |categ, sum| %>
    <% category_name = Category.find_by(id: categ).name %>
    <tr>
      <th scope="row"><%= num %></th>
      <td><%= category_name %></td>
      <td><%= sum %></td>
    </tr>
    <% num += 1 %>
    <% end %>
    <tr>
      <th scope="row"></th>
      <td><b>Total:</b></td>
      <td><b><%= @total %></b></td>
    </tr>
  </tbody>
</table>
</div>

  <%= render "pai_image" %>
</div>

app/views/reports/report_by_dates.html.erb
<div class="container-fluid">
  <h2>Financial Report by categories in the date range 
    <%= params[:start_date] %> - <%= params[:end_date] %></h2>

  <div>
  <canvas id="myChart" width="800" height="500"></canvas>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart');
  const data = {
  labels: <%= raw @data_date %>,
  datasets: [{
    label: 'Total spending by dates',
    data: <%= @data_sum %>,
    fill: false,
    borderColor: 'rgb(54, 162, 235)',
    tension: 0.1
  }]
};

const config = {
  type: 'line',
  data: data,
  options: {
    responsive: false
  }
};

const myChart = new Chart(ctx, config);
</script>   
  

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div style="color: red">
      <h3><%= pluralize(object.errors.count, "error") %> prohibited this category from being saved:</h3>

      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-white fixed-bottom">
  <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2); font-size: 18px">

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
  
    <a href="https://github.com/balerina09"><i class="fa fa-github"></i></a>  
   @kurgan <%= Time.now.year %>
   <a target="_blank" href="https://www.codewars.com/users/balerina09"><img src="https://www.codewars.com/users/balerina09/badges/micro" alt="codewars badge micro" /></a>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">CoinApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Operations', operations_path, class: 'nav-link' %>
        </li>  
          <li class="nav-item">
            <%= link_to 'Category', categories_path, class: 'nav-link' %>
          </li>
        <li class="nav-item">
          <%= link_to 'Reports', reports_index_path, class: 'nav-link' %>
        </li>
       </ul>
      </div>
  </div>
</nav>